kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mysql-router-volume
  namespace: doroob-staging
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 1Gi